version: '3.3'
services:
  irma:
    build:
      dockerfile: './irmago.Dockerfile'
      context: 'docker'
    expose: [8088]
    environment:
      TZ: Europe/Amsterdam
    networks:
      - default
    ports: ["0.0.0.0:8088:8088"]
    volumes:
      - ".:/app"
    command:
      - "irma"
      - "server"
      - "--verbose"
      - "--schemes-path=/app/.docker-irma-configuration"
      - "--schemes-assets-path=/app/irma-config"
      - "--schemes-update=0"
      - "--jwt-privkey-file=/app/irma-config/jwt_privkey.dev.pem"
      - "--url=${IRMA_URL}"

  nginx:
    image: nginx:1.19
    depends_on:
      - client
      - irma
      - server
    volumes:
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/certificates/server.pem:/etc/ssl/server.pem:ro"
      - "./docker/certificates/server.key:/etc/ssl/server.key:ro"
    ports:
      - 127.0.0.1:443:443
      - 127.0.0.1:80:80
      - 127.0.0.1:8080:8080
    environment:
      TZ: Europe/Amsterdam
    networks:
      default:
        aliases:
          - client.balie.test.tweede.golf
          - irma.balie.test.tweede.golf
          - server.balie.test.tweede.golf

  server:
    build:
      dockerfile: './go.Dockerfile'
      context: 'docker'
    volumes:
      - ".:/go/src/app:ro"
      - "/go/src/app/mrtd-unpack/.gradle"
      - "/go/src/app/mrtd-unpack/build"
    working_dir: /go/src/app/server
    networks:
      - default
    environment:
      BALIE_SERVER_DEBUGMODE: "true"
      BALIE_SERVER_IRMASERVER: http://irma:8088
      BALIE_SERVER_JWTSECRET: foo
      BALIE_SERVER_MRTDUNPACK: ../mrtd-unpack/run.dev.sh
      BALIE_SERVER_PASSPORTCREDENTIALID: "tweedegolf-demo.amsterdam.passport"
      BALIE_SERVER_IDCARDCREDENTIALID: "tweedegolf-demo.amsterdam.idcard"
      TZ: Europe/Amsterdam
    expose: [8081]

  client:
    build:
      dockerfile: './go.Dockerfile'
      context: 'docker'
    volumes:
      - ".:/go/src/app:ro"
      - "/go/src/app/mrtd-unpack/.gradle"
      - "/go/src/app/mrtd-unpack/build"
    working_dir: /go/src/app/client
    networks:
      - default
    environment:
      BALIE_CLIENT_DEBUGMODE: "true"
      BALIE_CLIENT_MRTDUNPACK: ../mrtd-unpack/run.dev.sh
      BALIE_CLIENT_SERVERADDRESS: http://server:8081
      TZ: Europe/Amsterdam
    expose: [8080]
