apiVersion: skaffold/v2beta9
kind: Config

build:
  artifacts:
  - image: registry.gitlab.com/stack11/commonground/irma-balie/balie-server
    context: .
    docker:
      dockerfile: balie-server/Dockerfile
  - image: registry.gitlab.com/stack11/commonground/irma-balie/irma-server
    context: irma-server
  local:
    useBuildkit: true
    concurrency: 0
    push: true

deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
    - name: irma-balie
      namespace: ""
      chartPath: helm/irma-balie
      artifactOverrides:
        imageBalieServer: registry.gitlab.com/stack11/commonground/irma-balie/balie-server
        imageIrmaServer: registry.gitlab.com/stack11/commonground/irma-balie/irma-server

profiles:

- name: prod
  deploy:
    kubeContext: gke_s11-company-prod_europe-west4_companycluster-prod
  patches:
  - op: add
    path: /deploy/helm/releases/0/valuesFiles
    value:
    - helm/irma-balie/values-prod.yaml
  - op: add
    path: /deploy/helm/releases/0/namespace
    value: irma-balie-prod

- name: test
  deploy:
    kubeContext: gke_s11-company-test_europe-west4-a_companycluster-test
  patches:
  - op: add
    path: /deploy/helm/releases/0/valuesFiles
    value:
    - helm/irma-balie/values-test.yaml
  - op: add
    path: /deploy/helm/releases/0/namespace
    value: irma-balie-test

- name: cicd
  build:
    local:
      useBuildkit: false
