apiVersion: skaffold/v3
kind: Config

build:
  artifacts:
    - image: balie-server
      context: .
      docker:
        dockerfile: balie-server/Dockerfile
    - image: irma-server
      context: irma-server
  local:
    useBuildkit: true
    concurrency: 0
    push: true

deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: irma-balie
        namespace: ""
        chartPath: helm/irma-balie
        setValueTemplates:
          imageBalieServer: "{{.IMAGE_FULLY_QUALIFIED_balie_server}}"
          imageIrmaServer: "{{.IMAGE_FULLY_QUALIFIED_irma_server}}"

profiles:
  - name: prod
    deploy:
      kubeContext: cluster-k8d4w
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - helm/irma-balie/values-prod.yaml
      - op: add
        path: /deploy/helm/releases/0/namespace
        value: irma-balie
