apiVersion: apps/v1
kind: Deployment
metadata:
  name: irma-server
  labels:
    {{- include "irmaBalie.labels" $ | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: irma-server
  template:
    metadata:
      labels:
        app: irma-server
    spec:
      initContainers:
        - name: copy-privkeys
          image: alpine:latest
          command: ["cp"]
          args: [
            "/privkeys-secret/0.xml",
            "/privkeys-secret/1.xml",
            "/privkeys-secret/2.xml",
            "/privkeys-secret/3.xml",
            "/privkeys"
          ]
          volumeMounts:
            - name: pilot-amsterdam-privkeys-secret
              mountPath: /privkeys-secret
              readOnly: true
            - name: pilot-amsterdam-privkeys
              mountPath: /privkeys
      containers:
        - name: irma-server
          image: {{$.Values.imageIrmaServer}}
          imagePullPolicy: IfNotPresent
          env: []
          args: [
            "/dist/irma",
            "server",
            "--port",        "8088",
            "--client-port", "8089",
            "--verbose",
            "--production",
            "--email",       "dillen@brainhive.nl",
            "--no-auth",     "true",
            "--issue-perms", "*",
            "--url",         "https://irma-server.{{$.Values.env}}.company.gcp.stack11.net",
            "--schemes-assets-path", "/dist/irma-assets",
            "--jwt-privkey-file", "/dist/jwt/jwt_privkey"
          ]
          volumeMounts:
            - name: jwt
              mountPath: /dist/jwt
              readOnly: true
            - name: pilot-amsterdam-privkeys
              mountPath: /dist/irma-assets/pbdf/pilot-amsterdam/PrivateKeys
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: github-registry
      volumes:
        - name: jwt
          secret:
            secretName: irma-server-jwt
        - name: pilot-amsterdam-privkeys
          emptyDir: {}
        - name: pilot-amsterdam-privkeys-secret
          secret:
            secretName: irma-server-pilot-amsterdam-privkeys
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: irma-server-internal
spec:
  type: ClusterIP
  selector:
    app: irma-server
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: irma-server-public
spec:
  type: ClusterIP
  selector:
    app: irma-server
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8089

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: irma-server
spec:
  secretName: tls-cert-irma-server
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-http
  dnsNames:
    - irma-server.{{ $.Values.env }}.company.gcp.stack11.net

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: irma-server
spec:
  parentRefs:
    - name: gateway
      namespace: envoy-gateway-system
  hostnames:
    - irma-server.{{ $.Values.env }}.company.gcp.stack11.net
  rules:
    - backendRefs:
      - name: irma-server-public
        port: 80
