---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: irma-server
  labels:
    {{- include "irmaBalie.labels" $ | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: irma-server
  template:
    metadata:
      labels:
        app: irma-server
    spec:
      # securityContext:
      #   runAsUser: 1001 # TODO
      initContainers:
        - name: copy-privkeys
          image: alpine:latest
          command: ["cp"]
          args: [
            "/privkeys-secret/0.xml",
            "/privkeys-secret/1.xml",
            "/privkeys-secret/2.xml",
            "/privkeys"
          ]
          volumeMounts:
            - name: pilot-amsterdam-privkeys-secret
              mountPath: /privkeys-secret
              readOnly: true
            - name: pilot-amsterdam-privkeys
              mountPath: /privkeys
      containers:
        - name: irma-server
          image: {{$.Values.imageIrmaServer}}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 800m
          env: []
          args: [
            "/dist/irma",
            "server",
            "--port",        "8088",
            "--client-port", "8089",
            "--verbose",
            "--production",
            "--email",       "dillen@stack11.io",
            "--no-auth",     "true",
            "--issue-perms", "*",
            "--url",         "https://irma-server.{{$.Values.env}}.company.gcp.stack11.net",
            "--schemes-assets-path", "/dist/irma-assets",
            "--jwt-privkey-file", "/dist/jwt/jwt_privkey"
          ]
          volumeMounts:
            - name: jwt
              mountPath: /dist/jwt
              readOnly: true
            - name: pilot-amsterdam-privkeys
              mountPath: /dist/irma-assets/pbdf/pilot-amsterdam/PrivateKeys
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 1
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 1

      imagePullSecrets:
        - name: github-registry
      volumes:
        - name: jwt
          secret:
            secretName: irma-server-jwt
        - name: pilot-amsterdam-privkeys
          emptyDir: {}
        - name: pilot-amsterdam-privkeys-secret
          secret:
            secretName: irma-server-pilot-amsterdam-privkeys
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: irma-server-internal
spec:
  type: ClusterIP
  selector:
    app: irma-server
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: irma-server-public
spec:
  type: ClusterIP
  selector:
    app: irma-server
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8089
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: irma-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - irma-server.{{$.Values.env}}.company.gcp.stack11.net
      secretName: irma-server.{{$.Values.env}}.company.gcp.stack11.net
  rules:
    - host: irma-server.{{$.Values.env}}.company.gcp.stack11.net
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: irma-server-public
                port:
                  number: 80
